---
apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  labels:
    app: bind9
spec:
  type: NodePort
  selector:
    app: bind9
  ports:
  - port: 53
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
      - name: bind9
        image: ubuntu/bind9:edge
        env:
        ports:
        - containerPort: 53
          name: bind9
          protocol: TCP
