---
apiVersion: v1
kind: Service
metadata:
  name: console1
spec:
  selector:
    app: minio1
  type: NodePort
  ports:
    - name: ui1
      protocol: TCP
      port: 9091
      targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: console2
spec:
  selector:
    app: minio2
  type: NodePort
  ports:
    - name: ui2
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: console3
spec:
  selector:
    app: minio3
  type: NodePort
  ports:
    - name: ui3
      protocol: TCP
      port: 9093
      targetPort: 9093
