apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite
  labels:
    app: graphite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphite
  template:
    metadata:
      labels:
        app: graphite
    spec:
      containers:
      - name: graphite
        image: graphiteapp/graphite-statsd
        ports:
          - containerPort: 80
          - containerPort: 2003
          - containerPort: 2004
          - containerPort: 2023
          - containerPort: 2024
          - containerPort: 8125
          - containerPort: 8126
      - name: grafana
        image: grafana/grafana-oss
        ports:
          - containerPort: 3000
